site_name: "Great Expectations Guardian Workload"
site_description: "Template to create a component out of Great Expectations Guardian Workload Template"

nav:
  - Template Usage: index.md

plugins:
  - techdocs-core